baseURL = 'https://voloyev.github.io/'
languageCode = 'en-us'
title = 'Notes'
theme = 'archie'

[services]
  [services.googleAnalytics]
    ID = 'G-FFLK202G5N'  # Replace with your GA4 measurement ID

[markup]
  [markup.highlight]
    style = 'gruvbox-light'
